# Generated by Django 5.2.4 on 2025-07-13 02:27

import django.contrib.auth.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Nombre de usuario')),
                ('nombre_completo', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('email', models.EmailField(error_messages={'blank': 'El correo electrónico es obligatorio.', 'null': 'El correo electrónico es obligatorio.', 'unique': 'Este correo electrónico ya está registrado.'}, max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='El número de celular debe contener entre 7 y 15 dígitos numéricos.', regex='^\\d{7,15}$')], verbose_name='Número de celular')),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Imagen de perfil')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
