# Generated by Django 5.2.4 on 2025-07-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodesarrollo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, error_messages={'blank': 'El correo electrónico es obligatorio.', 'null': 'El correo electrónico es obligatorio.', 'unique': 'Este correo electrónico ya está registrado.'}, max_length=254, null=True, unique=True, verbose_name='Correo electrónico'),
        ),
    ]
