# Generated by Django 5.2.4 on 2025-07-13 03:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodesarrollo', '0003_alter_usuario_email_alter_usuario_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El número de celular debe contener entre 7 y 15 dígitos numéricos.', regex='^\\d{7,15}$')]),
        ),
    ]
