# Generated by Django 5.2.4 on 2025-07-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodesarrollo', '0004_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_verificacion',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email_verificado',
            field=models.BooleanField(default=False),
        ),
    ]
