# Generated by Django 5.2.4 on 2025-07-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodesarrollo', '0007_seguimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen_perfil',
            field=models.ImageField(blank=True, default='perfiles/default.jpg', null=True, upload_to='perfiles/'),
        ),
    ]
