# Generated by Django 5.2.4 on 2025-07-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodesarrollo', '0008_alter_usuario_imagen_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen_perfil',
            field=models.ImageField(blank=True, default='perfiles/perfil_default.jpg', null=True, upload_to='perfiles/'),
        ),
    ]
