# Generated by Django 5.2.4 on 2025-07-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodesarrollo', '0009_alter_usuario_imagen_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'Prefiero no decirlo')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='presentacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
