# Generated by Django 5.2.4 on 2025-07-15 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodesarrollo', '0010_usuario_edad_usuario_genero_usuario_presentacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='presentacion',
            new_name='descripción',
        ),
    ]
