# Generated by Django 5.2.4 on 2025-07-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodesarrollo', '0012_publicacion_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Publicación', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='imagen',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='publicaciones/', verbose_name='Imagen/Video'),
        ),
    ]
