# Generated by Django 5.2.4 on 2025-07-29 20:48

import django.db.models.deletion
import django.utils.timezone
import prodesarrollo.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodesarrollo', '0016_alter_usuario_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='reels/videos/', validators=[prodesarrollo.models.validate_video])),
                ('miniatura', models.ImageField(blank=True, null=True, upload_to='reels/thumbs/')),
                ('titulo', models.CharField(blank=True, max_length=150)),
                ('audio_titulo', models.CharField(blank=True, max_length=150)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('vistas', models.PositiveIntegerField(default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reels', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='reels_likeados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
