# Generated by Django 5.2.4 on 2025-07-31 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodesarrollo', '0017_reel'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivopublicacion',
            name='aspect_ratio',
            field=models.CharField(choices=[('4:5', '4:5'), ('16:9', '16:9')], default='4:5', max_length=10),
        ),
    ]
